<?php

/**
 * BaseCategorie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $nom
 * @property string $description
 * @property string $logo
 * @property integer $weight
 * @property boolean $in_menu
 * @property Doctrine_Collection $Promotions
 * 
 * @method string              getUrl()         Returns the current record's "url" value
 * @method string              getNom()         Returns the current record's "nom" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getLogo()        Returns the current record's "logo" value
 * @method integer             getWeight()      Returns the current record's "weight" value
 * @method boolean             getInMenu()      Returns the current record's "in_menu" value
 * @method Doctrine_Collection getPromotions()  Returns the current record's "Promotions" collection
 * @method Categorie           setUrl()         Sets the current record's "url" value
 * @method Categorie           setNom()         Sets the current record's "nom" value
 * @method Categorie           setDescription() Sets the current record's "description" value
 * @method Categorie           setLogo()        Sets the current record's "logo" value
 * @method Categorie           setWeight()      Sets the current record's "weight" value
 * @method Categorie           setInMenu()      Sets the current record's "in_menu" value
 * @method Categorie           setPromotions()  Sets the current record's "Promotions" collection
 * 
 * @package    edt
 * @subpackage model
 * @author     Théophile Helleboid, Michael Muré
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategorie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categorie');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('logo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('weight', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('in_menu', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Promotion as Promotions', array(
             'local' => 'id',
             'foreign' => 'categorie_id'));
    }
}