<?php

/**
 * BasePromotion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $nom
 * @property string $description
 * @property integer $categorie_id
 * @property integer $weight
 * @property boolean $in_menu
 * @property string $id_tree
 * @property string $branch_id
 * @property string $select_branch_id
 * @property string $select_id
 * @property Categorie $Categorie
 * @property Doctrine_Collection $Messages
 * 
 * @method string              getUrl()              Returns the current record's "url" value
 * @method string              getNom()              Returns the current record's "nom" value
 * @method string              getDescription()      Returns the current record's "description" value
 * @method integer             getCategorieId()      Returns the current record's "categorie_id" value
 * @method integer             getWeight()           Returns the current record's "weight" value
 * @method boolean             getInMenu()           Returns the current record's "in_menu" value
 * @method string              getIdTree()           Returns the current record's "id_tree" value
 * @method string              getBranchId()         Returns the current record's "branch_id" value
 * @method string              getSelectBranchId()   Returns the current record's "select_branch_id" value
 * @method string              getSelectId()         Returns the current record's "select_id" value
 * @method Categorie           getCategorie()        Returns the current record's "Categorie" value
 * @method Doctrine_Collection getMessages()         Returns the current record's "Messages" collection
 * @method Promotion           setUrl()              Sets the current record's "url" value
 * @method Promotion           setNom()              Sets the current record's "nom" value
 * @method Promotion           setDescription()      Sets the current record's "description" value
 * @method Promotion           setCategorieId()      Sets the current record's "categorie_id" value
 * @method Promotion           setWeight()           Sets the current record's "weight" value
 * @method Promotion           setInMenu()           Sets the current record's "in_menu" value
 * @method Promotion           setIdTree()           Sets the current record's "id_tree" value
 * @method Promotion           setBranchId()         Sets the current record's "branch_id" value
 * @method Promotion           setSelectBranchId()   Sets the current record's "select_branch_id" value
 * @method Promotion           setSelectId()         Sets the current record's "select_id" value
 * @method Promotion           setCategorie()        Sets the current record's "Categorie" value
 * @method Promotion           setMessages()         Sets the current record's "Messages" collection
 * 
 * @package    edt
 * @subpackage model
 * @author     Théophile Helleboid, Michael Muré
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePromotion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('promotion');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('categorie_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('weight', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('in_menu', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('id_tree', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('branch_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('select_branch_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('select_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->index('url', array(
             'fields' => 
             array(
              0 => 'url',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Categorie', array(
             'local' => 'categorie_id',
             'foreign' => 'id'));

        $this->hasMany('Message as Messages', array(
             'local' => 'id',
             'foreign' => 'promotion_id'));
    }
}