<?php

/**
 * BasePromotion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $nom
 * @property string $description
 * @property integer $filiere_id
 * @property string $conf_trees
 * @property Filiere $Filiere
 * 
 * @method string    getUrl()         Returns the current record's "url" value
 * @method string    getNom()         Returns the current record's "nom" value
 * @method string    getDescription() Returns the current record's "description" value
 * @method integer   getFiliereId()   Returns the current record's "filiere_id" value
 * @method string    getConfTrees()   Returns the current record's "conf_trees" value
 * @method Filiere   getFiliere()     Returns the current record's "Filiere" value
 * @method Promotion setUrl()         Sets the current record's "url" value
 * @method Promotion setNom()         Sets the current record's "nom" value
 * @method Promotion setDescription() Sets the current record's "description" value
 * @method Promotion setFiliereId()   Sets the current record's "filiere_id" value
 * @method Promotion setConfTrees()   Sets the current record's "conf_trees" value
 * @method Promotion setFiliere()     Sets the current record's "Filiere" value
 * 
 * @package    edt
 * @subpackage model
 * @author     Théophile Helleboid, Michael Muré
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BasePromotion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('promotion');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('filiere_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('conf_trees', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Filiere', array(
             'local' => 'filiere_id',
             'foreign' => 'id'));
    }
}