<?php

/**
 * BaseAdeserver
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nom
 * @property string $description
 * @property string $identifier
 * @property string $ade_url
 * @property string $login
 * @property Doctrine_Collection $Edts
 * 
 * @method string              getNom()         Returns the current record's "nom" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getIdentifier()  Returns the current record's "identifier" value
 * @method string              getAdeUrl()      Returns the current record's "ade_url" value
 * @method string              getLogin()       Returns the current record's "login" value
 * @method Doctrine_Collection getEdts()        Returns the current record's "Edts" collection
 * @method Adeserver           setNom()         Sets the current record's "nom" value
 * @method Adeserver           setDescription() Sets the current record's "description" value
 * @method Adeserver           setIdentifier()  Sets the current record's "identifier" value
 * @method Adeserver           setAdeUrl()      Sets the current record's "ade_url" value
 * @method Adeserver           setLogin()       Sets the current record's "login" value
 * @method Adeserver           setEdts()        Sets the current record's "Edts" collection
 * 
 * @package    edt
 * @subpackage model
 * @author     Théophile Helleboid, Michael Muré
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdeserver extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('adeserver');
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('identifier', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('ade_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('login', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Edt as Edts', array(
             'local' => 'id',
             'foreign' => 'adeserver_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}