<?php

/**
 * BasePromotion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $nom
 * @property string $description
 * @property integer $filiere_id
 * @property string $id_tree
 * @property string $branch_id
 * @property string $select_branch_id
 * @property string $select_id
 * @property string $id_piano_day
 * @property integer $width
 * @property integer $height
 * @property Filiere $Filiere
 * 
 * @method string    getUrl()              Returns the current record's "url" value
 * @method string    getNom()              Returns the current record's "nom" value
 * @method string    getDescription()      Returns the current record's "description" value
 * @method integer   getFiliereId()        Returns the current record's "filiere_id" value
 * @method string    getIdTree()           Returns the current record's "id_tree" value
 * @method string    getBranchId()         Returns the current record's "branch_id" value
 * @method string    getSelectBranchId()   Returns the current record's "select_branch_id" value
 * @method string    getSelectId()         Returns the current record's "select_id" value
 * @method string    getIdPianoDay()       Returns the current record's "id_piano_day" value
 * @method integer   getWidth()            Returns the current record's "width" value
 * @method integer   getHeight()           Returns the current record's "height" value
 * @method Filiere   getFiliere()          Returns the current record's "Filiere" value
 * @method Promotion setUrl()              Sets the current record's "url" value
 * @method Promotion setNom()              Sets the current record's "nom" value
 * @method Promotion setDescription()      Sets the current record's "description" value
 * @method Promotion setFiliereId()        Sets the current record's "filiere_id" value
 * @method Promotion setIdTree()           Sets the current record's "id_tree" value
 * @method Promotion setBranchId()         Sets the current record's "branch_id" value
 * @method Promotion setSelectBranchId()   Sets the current record's "select_branch_id" value
 * @method Promotion setSelectId()         Sets the current record's "select_id" value
 * @method Promotion setIdPianoDay()       Sets the current record's "id_piano_day" value
 * @method Promotion setWidth()            Sets the current record's "width" value
 * @method Promotion setHeight()           Sets the current record's "height" value
 * @method Promotion setFiliere()          Sets the current record's "Filiere" value
 * 
 * @package    edt
 * @subpackage model
 * @author     Théophile Helleboid, Michael Muré
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePromotion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('promotion');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('filiere_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_tree', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('branch_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('select_branch_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('select_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('id_piano_day', 'string', 255, array(
             'type' => 'string',
             'default' => '0,1,2,3,4',
             'length' => 255,
             ));
        $this->hasColumn('width', 'integer', null, array(
             'type' => 'integer',
             'default' => 800,
             ));
        $this->hasColumn('height', 'integer', null, array(
             'type' => 'integer',
             'default' => 600,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Filiere', array(
             'local' => 'filiere_id',
             'foreign' => 'id'));
    }
}