<?php

/**
 * BaseFiliere
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $nom
 * @property string $description
 * @property string $logo
 * @property Doctrine_Collection $Promotions
 * 
 * @method string              getUrl()         Returns the current record's "url" value
 * @method string              getNom()         Returns the current record's "nom" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getLogo()        Returns the current record's "logo" value
 * @method Doctrine_Collection getPromotions()  Returns the current record's "Promotions" collection
 * @method Filiere             setUrl()         Sets the current record's "url" value
 * @method Filiere             setNom()         Sets the current record's "nom" value
 * @method Filiere             setDescription() Sets the current record's "description" value
 * @method Filiere             setLogo()        Sets the current record's "logo" value
 * @method Filiere             setPromotions()  Sets the current record's "Promotions" collection
 * 
 * @package    edt
 * @subpackage model
 * @author     Théophile Helleboid, Michael Muré
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseFiliere extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('filiere');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('logo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Promotion as Promotions', array(
             'local' => 'id',
             'foreign' => 'filiere_id'));
    }
}