<?php

/**
 * BaseMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $texte
 * @property integer $promotion_id
 * @property integer $semaine
 * @property Promotion $Promotion
 * 
 * @method string    getTexte()        Returns the current record's "texte" value
 * @method integer   getPromotionId()  Returns the current record's "promotion_id" value
 * @method integer   getSemaine()      Returns the current record's "semaine" value
 * @method Promotion getPromotion()    Returns the current record's "Promotion" value
 * @method Message   setTexte()        Sets the current record's "texte" value
 * @method Message   setPromotionId()  Sets the current record's "promotion_id" value
 * @method Message   setSemaine()      Sets the current record's "semaine" value
 * @method Message   setPromotion()    Sets the current record's "Promotion" value
 * 
 * @package    edt
 * @subpackage model
 * @author     Théophile Helleboid, Michael Muré
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('message');
        $this->hasColumn('texte', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('promotion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('semaine', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Promotion', array(
             'local' => 'promotion_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}