<?php

/**
 * AdeserverTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdeserverTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdeserverTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Adeserver');
    }
}