<?php

/**
 * CategorieTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategorieTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategorieTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Categorie');
    }
}