<?php

/**
 * EdtTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EdtTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EdtTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Edt');
    }
}