<?php

/**
 * Filiere
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    edt
 * @subpackage model
 * @author     Théophile Helleboid, Michael Muré
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Filiere extends BaseFiliere
{
  public function __toString()
  {
    return $this->getNom();
  }
}
