<?php

/**
 * PromotionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PromotionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PromotionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Promotion');
    }
}