<?php

/**
 * PromotionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PromotionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PromotionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Promotion');
    }

    public function createQuery($alias = '')
    {
      if(defined('NOM_EDT'))
        return parent::createQuery($alias)
          ->leftJoin($alias.'.Categorie cat')
          ->leftJoin('cat.Edt e')
          ->where('e.nom = ?', NOM_EDT);
      else
        return parent::createQuery($alias);
    }
}